"""Domain entities and value objects.

Convention reminders encoded here:
- Entity identity is always a UUID (annotations are never addressed by index).
- Asset content identity is the SHA-256 hash of the bytes.
- Coordinates live in the asset's native reference frame (pixels for images);
  normalization is an exporter concern.
"""

from visionset.kernel.domain.annotation import Annotation, Provenance
from visionset.kernel.domain.asset import Asset
from visionset.kernel.domain.batch import (
    BATCH_TRANSITIONS,
    CORRECTABLE_STATES,
    DELETABLE_STATES,
    EDITABLE_STATES,
    PROMOTABLE_STATES,
    REPINNABLE_STATES,
    Batch,
    BatchState,
)
from visionset.kernel.domain.capabilities import (
    ASSET_MOVES,
    BATCH_GATES,
    BATCH_MOVES,
    JOB_MOVES,
    UNNAMED_EDGES,
    AssetAction,
    BatchAction,
    JobAction,
    Move,
    asset_actions,
    batch_actions,
    job_actions,
)
from visionset.kernel.domain.dataset import (
    ClassCount,
    Dataset,
    DatasetChange,
    DatasetMember,
    DatasetOperation,
    DatasetStats,
)
from visionset.kernel.domain.events import (
    AnnotationOperation,
    AnnotationsWritten,
    BatchApproved,
    BatchCompleted,
    DomainEvent,
    IngestCompleted,
    ReleasePublished,
)
from visionset.kernel.domain.geometry import (
    IMPLEMENTED_GEOMETRIES,
    BboxGeometry,
    ClassificationGeometry,
    Geometry,
    PolygonGeometry,
)
from visionset.kernel.domain.ingest import (
    INGEST_TRANSITIONS,
    IngestFailure,
    IngestFailureKind,
    IngestJob,
    IngestResult,
    IngestState,
    ThumbnailBackfill,
    report_name,
)
from visionset.kernel.domain.media import (
    ImageFormat,
    ImageMetadata,
    VideoFrame,
    VideoMetadata,
)
from visionset.kernel.domain.names import normalize_name
from visionset.kernel.domain.partition import (
    BySegments,
    BySize,
    Partition,
    SingleJob,
    partition_assets,
)
from visionset.kernel.domain.project import Project, ProjectStats
from visionset.kernel.domain.release import (
    MANIFEST_VERSION,
    ClassCompatibility,
    ClassExportStatus,
    ExportCompatibility,
    ExportResult,
    Manifest,
    ManifestAnnotation,
    ManifestAsset,
    Release,
    ReleaseVerification,
    SplitAssignment,
    SplitRecipe,
    assign_split,
    canonical_bytes,
    sha256_hex,
)
from visionset.kernel.domain.schema import (
    AnnotationSchema,
    Attribute,
    AttributeValue,
    GeometryType,
    LabelClass,
)
from visionset.kernel.domain.schema_diff import (
    ChangeKind,
    SchemaChange,
    SchemaDiff,
    diff_classes,
)
from visionset.kernel.domain.source import (
    Source,
    SourceKind,
    VideoProvenance,
    canonical_path,
)
from visionset.kernel.domain.task import (
    ASSET_PROGRESS_TRANSITIONS,
    JOB_TRANSITIONS,
    PROMOTABLE_PROGRESS,
    SETTLED_PROGRESS,
    WRITABLE_PROGRESS,
    AnnotationJob,
    AnnotationJobState,
    AssetProgress,
    TaskGroup,
    progress_after_annotating,
)
from visionset.kernel.domain.token import (
    SECRET_BYTES,
    SECRET_PREFIX,
    IssuedToken,
    Token,
    generate_secret,
    hash_secret,
)
from visionset.kernel.domain.transitions import require_move, require_state
from visionset.kernel.domain.workspace import Workspace

__all__ = [
    "job_actions",
    "batch_actions",
    "asset_actions",
    "Move",
    "JobAction",
    "BatchAction",
    "AssetAction",
    "UNNAMED_EDGES",
    "JOB_MOVES",
    "BATCH_MOVES",
    "BATCH_GATES",
    "ASSET_MOVES",
    "ASSET_PROGRESS_TRANSITIONS",
    "BATCH_TRANSITIONS",
    "CORRECTABLE_STATES",
    "DELETABLE_STATES",
    "EDITABLE_STATES",
    "IMPLEMENTED_GEOMETRIES",
    "INGEST_TRANSITIONS",
    "JOB_TRANSITIONS",
    "MANIFEST_VERSION",
    "PROMOTABLE_PROGRESS",
    "PROMOTABLE_STATES",
    "REPINNABLE_STATES",
    "SECRET_BYTES",
    "SECRET_PREFIX",
    "SETTLED_PROGRESS",
    "WRITABLE_PROGRESS",
    "Annotation",
    "AnnotationJob",
    "AnnotationJobState",
    "AnnotationOperation",
    "AnnotationSchema",
    "AnnotationsWritten",
    "Asset",
    "AssetProgress",
    "Attribute",
    "AttributeValue",
    "Batch",
    "BatchApproved",
    "BatchCompleted",
    "BatchState",
    "BboxGeometry",
    "BySegments",
    "BySize",
    "ChangeKind",
    "ClassCount",
    "ClassificationGeometry",
    "Dataset",
    "DatasetChange",
    "DatasetMember",
    "DatasetOperation",
    "DatasetStats",
    "DomainEvent",
    "ClassCompatibility",
    "ClassExportStatus",
    "ExportCompatibility",
    "ExportResult",
    "Geometry",
    "GeometryType",
    "ImageFormat",
    "ImageMetadata",
    "IngestCompleted",
    "IngestFailure",
    "IngestFailureKind",
    "IngestJob",
    "IngestResult",
    "IngestState",
    "IssuedToken",
    "LabelClass",
    "Manifest",
    "ManifestAnnotation",
    "ManifestAsset",
    "Partition",
    "PolygonGeometry",
    "Project",
    "ProjectStats",
    "Provenance",
    "Release",
    "ReleasePublished",
    "ReleaseVerification",
    "SchemaChange",
    "SchemaDiff",
    "SingleJob",
    "Source",
    "SourceKind",
    "SplitAssignment",
    "SplitRecipe",
    "TaskGroup",
    "ThumbnailBackfill",
    "Token",
    "VideoFrame",
    "VideoMetadata",
    "VideoProvenance",
    "Workspace",
    "assign_split",
    "canonical_bytes",
    "canonical_path",
    "diff_classes",
    "generate_secret",
    "hash_secret",
    "normalize_name",
    "partition_assets",
    "progress_after_annotating",
    "report_name",
    "require_move",
    "require_state",
    "sha256_hex",
]
