"""No media binary enters git again — v1's history carries 929 MB of fixture images.

`.gitignore` blocks `**/workspace-data/` and CONTRIBUTING.md says never to commit fixture
media, but prose does not fail a build. This does. Fixtures are generated at runtime instead;
`tests/fixtures/media.py` is the sanctioned way to get one.

`git ls-files` reads the *index*, so a binary that is merely staged already trips the guard —
it fires before the commit lands, which is the whole point.
"""

import subprocess
from collections.abc import Mapping
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]

MAX_TRACKED_BYTES = 200 * 1024

ALLOWLIST: dict[str, int] = {
    # The resolved dependency graph for the whole workspace: text, machine-generated, and being
    # large is the file's job. Bounded anyway, so it cannot balloon unnoticed.
    "uv.lock": 1024 * 1024,
    # The API contract, regenerated by scripts/export_openapi.py and gated against drift in CI.
    # Same shape of exemption as uv.lock: text, machine-generated, and its size is a function of
    # how many operations the API has rather than of anything anybody chose. It crossed the
    # default limit at 53 operations, running ~4 KB apiece; this ceiling is roughly 120 more.
    #
    # It is a *ceiling*, not a licence. If this one is ever hit the question is whether the API
    # really grew that much, and the answer is not another zero here.
    "openapi.json": 512 * 1024,
    # The typed client, regenerated by scripts/generate_client.mjs from openapi.json and gated
    # against drift in CI. Third of the same shape: text, machine-generated, and a function of how
    # many operations the API has. Listed at 194 KB — *inside* the default limit by 6 KB, which is
    # about one endpoint. Waiting for it to trip would mean the next surface task discovering a
    # media guard it has nothing to do with, so the exemption is taken deliberately now rather
    # than under duress later. Same ceiling as the spec it is derived from.
    "frontend/ui-core/src/generated/api.ts": 512 * 1024,
    # The frontend workspace's resolved dependency graph — the pnpm counterpart of uv.lock, and
    # exempted on the same terms: text, machine-generated, and being large is the file's job. It
    # lived under the default limit until the shadcn preset foundation brought its dependencies
    # (the shadcn runtime, two font packages, an icon set) and pushed it to 219 KB, which is how
    # a media guard came to refuse a lockfile. Bounded like the others, so it cannot balloon
    # unnoticed.
    "pnpm-lock.yaml": 1024 * 1024,
    # The documentation site's resolved dependency graph. `docs-site/` is its own pnpm workspace
    # root, so it keeps its own lockfile — see docs-site/pnpm-workspace.yaml for why. Same
    # exemption as uv.lock and for the same reason: text, machine-generated, and being large is
    # the file's job.
    #
    # Taken on the same terms the generated client's entry above argues for. It lands at 164 KB,
    # inside the default limit by about 36 KB — which is a dependency or two, and Astro brings
    # dependencies. Left to trip on its own, the failure would land on some later Dependabot bump
    # as a *media* guard refusing a lockfile, which reads as a broken check rather than as a
    # deliberate limit.
    "docs-site/pnpm-lock.yaml": 1024 * 1024,
}
"""Path -> its own ceiling. An entry here is a deliberate exception and owes a reason above it;
an exemption raises the limit for one file, it never removes it."""


def tracked_file_sizes() -> dict[str, int]:
    result = subprocess.run(
        ["git", "-C", str(REPO_ROOT), "ls-files", "-z"],
        capture_output=True,
        text=True,
        check=True,
    )
    paths = [line for line in result.stdout.split("\0") if line]
    return {
        path: (REPO_ROOT / path).stat().st_size for path in paths if (REPO_ROOT / path).is_file()
    }


def oversized(sizes: Mapping[str, int]) -> dict[str, tuple[int, int]]:
    """The rule itself, as a pure function, so it can be proven without touching git."""
    return {
        path: (size, ALLOWLIST.get(path, MAX_TRACKED_BYTES))
        for path, size in sizes.items()
        if size > ALLOWLIST.get(path, MAX_TRACKED_BYTES)
    }


def _report(offenders: Mapping[str, tuple[int, int]]) -> str:
    lines = [
        f"  {path}: {size:,} bytes (limit {ceiling:,})"
        for path, (size, ceiling) in sorted(offenders.items())
    ]
    return "\n".join([f"{len(offenders)} tracked file(s) over the size limit:", *lines])


def test_no_tracked_file_exceeds_the_size_limit() -> None:
    if not (REPO_ROOT / ".git").exists():
        pytest.skip("not a git checkout, so there is no index to inspect")
    offenders = oversized(tracked_file_sizes())
    assert not offenders, (
        f"{_report(offenders)}\n"
        "Generate media at runtime with tests/fixtures/media.py instead of committing it. "
        "If the file genuinely belongs in git, add it to ALLOWLIST with a reason."
    )


def test_the_guard_reports_a_file_that_exceeds_the_limit() -> None:
    """The issue asks for proof the guard fails on a deliberately added binary. This is that
    proof in permanent form — no binary needed, and it cannot rot out of the suite."""
    offenders = oversized({"README.md": 2_764, "tests/fixtures/cat.jpg": 5 * 1024 * 1024})
    assert list(offenders) == ["tests/fixtures/cat.jpg"]
    assert offenders["tests/fixtures/cat.jpg"] == (5 * 1024 * 1024, MAX_TRACKED_BYTES)


def test_an_allowlisted_file_is_still_bounded() -> None:
    """An exemption is a higher ceiling, not a blank cheque."""
    ceiling = ALLOWLIST["uv.lock"]
    assert not oversized({"uv.lock": ceiling})
    assert oversized({"uv.lock": ceiling + 1}) == {"uv.lock": (ceiling + 1, ceiling)}


def test_every_allowlist_entry_is_still_tracked() -> None:
    """An entry naming a file nobody tracks any more is rot, and rot hides the next exception."""
    if not (REPO_ROOT / ".git").exists():
        pytest.skip("not a git checkout, so there is no index to inspect")
    tracked = tracked_file_sizes()
    assert not [path for path in ALLOWLIST if path not in tracked]
