/**
 * A test-only harness proving the displayed asset is the browser pixel source.
 *
 * `docs/content/architecture/frontend/ui-core.md`'s rule — the visible `<img>` is
 * reused as the browser pixel source, with no second fetch and no independent
 * decode — has one half no unit test can reach: jsdom's canvas does not decode a
 * real image, so `getImageData` there is either absent or a stub a test supplies
 * itself. This page composes the real `AssetImage` and `AnnotatorCanvas` exactly
 * as `AnnotationPage` does, against a tiny RGBA image **encoded to a PNG blob at
 * runtime** (no binary fixture file, so the exact bytes are never stale or
 * regenerated by hand) — so `e2e/assetPixels.spec.ts` can prove the seam in a
 * real browser: one content request, the same decoded `<img>` handed back as the
 * pixel source, and the exact descriptor-frame RGB a real canvas produced.
 *
 * No token, no server, not linked from anywhere in the product — the same
 * standing as `/demo` and `/styleguide`.
 */

import { AnnotatorCanvas, AnnotatorStore, documentFromWire } from "@visionset/annotator";
import { AssetImage, VisionSetDataProvider } from "@visionset/ui-core";
import type { DataResult, VisionSetDataClient } from "@visionset/ui-core";
import { useEffect, useMemo, useState, type JSX } from "react";

declare global {
  interface Window {
    /** How many times the stub client has delivered content. Reset on load. */
    __assetContentRequests?: number;
  }
}

const PROJECT_ID = "fixture-project";
const ASSET_ID = "fixture-asset";
const WIDTH = 3;
const HEIGHT = 1;

/**
 * Three RGBA pixels, alpha fully opaque.
 *
 * A low alpha would make the PNG round-trip lossy — canvas premultiplies alpha
 * on encode, and an opaque pixel is the one value that survives unpremultiplying
 * exactly. `1,2,3` / `5,6,7` / `9,10,11` is what `pixel-rgb` below must read back
 * once the fourth (alpha) byte of each RGBA quadruple is dropped.
 */
const RGBA = new Uint8ClampedArray([1, 2, 3, 255, 5, 6, 7, 255, 9, 10, 11, 255]);

function fixtureStore(): AnnotatorStore {
  return new AnnotatorStore(
    documentFromWire({
      asset: { id: ASSET_ID, width: WIDTH, height: HEIGHT },
      schema: { project_id: PROJECT_ID, version: 1, classes: [] },
      annotations: [],
    }),
  );
}

/** A real PNG, built from the exact bytes above — never a checked-in fixture. */
async function encodeFixturePng(): Promise<Blob> {
  const canvas = document.createElement("canvas");
  canvas.width = WIDTH;
  canvas.height = HEIGHT;
  const context = canvas.getContext("2d");
  if (context === null) throw new Error("2D canvas context is unavailable");
  context.putImageData(new ImageData(RGBA, WIDTH, HEIGHT), 0, 0);
  return await new Promise<Blob>((resolve, reject) => {
    canvas.toBlob((blob) => {
      if (blob === null) reject(new Error("canvas produced no blob"));
      else resolve(blob);
    }, "image/png");
  });
}

/**
 * A minimal `VisionSetDataClient`: it answers the one route `AssetImage` calls,
 * counts a delivery only once it actually settles, and rejects a request whose
 * signal is already or becomes aborted — the same contract clause a real host
 * honours (`data/port.ts`'s "a request cancelled through its signal rejects").
 *
 * Delivery is deferred one macrotask so a synchronous `StrictMode` remount's
 * cleanup — the abort of the first mount's controller — has already landed on
 * `signal` before this settles, the ordering a real network transfer has for
 * free. Without it, a mutation that dropped the abort could still read as one
 * request here purely by winning a race, which would prove nothing.
 */
function fixtureClient(png: Blob, onDelivered: () => void): VisionSetDataClient {
  const GET = (path: string, init?: { readonly signal?: AbortSignal }): Promise<DataResult> => {
    if (!path.endsWith("/content")) return Promise.resolve({ ok: false, failure: "unreachable" });
    const signal = init?.signal;
    return new Promise<DataResult>((resolve, reject) => {
      if (signal?.aborted === true) {
        reject(new DOMException("The operation was aborted.", "AbortError"));
        return;
      }
      const onAbort = (): void => {
        window.clearTimeout(timer);
        reject(new DOMException("The operation was aborted.", "AbortError"));
      };
      const timer = window.setTimeout(() => {
        signal?.removeEventListener("abort", onAbort);
        if (signal?.aborted === true) {
          reject(new DOMException("The operation was aborted.", "AbortError"));
          return;
        }
        onDelivered();
        resolve({ ok: true, data: png });
      }, 0);
      signal?.addEventListener("abort", onAbort, { once: true });
    });
  };
  const refuse = (): Promise<DataResult> => Promise.resolve({ ok: false, failure: "unreachable" });
  return {
    GET,
    POST: refuse,
    PUT: refuse,
    PATCH: refuse,
    DELETE: refuse,
  } as unknown as VisionSetDataClient;
}

export function AssetPixelsFixture(): JSX.Element {
  const [png, setPng] = useState<Blob | null>(null);
  const [sameImage, setSameImage] = useState("pending");
  const [rgb, setRgb] = useState("pending");
  const store = useMemo(fixtureStore, []);

  useEffect(() => {
    window.__assetContentRequests = 0;
    let cancelled = false;
    void encodeFixturePng().then((blob) => {
      if (!cancelled) setPng(blob);
    });
    return () => {
      cancelled = true;
    };
  }, []);

  const client = useMemo(() => {
    if (png === null) return null;
    return fixtureClient(png, () => {
      window.__assetContentRequests = (window.__assetContentRequests ?? 0) + 1;
    });
  }, [png]);

  if (client === null) return <div data-testid="asset-pixels-fixture-loading" />;

  return (
    <VisionSetDataProvider client={client} scope="asset-pixels-fixture">
      <div style={{ width: 120, height: 40 }}>
        <AssetImage projectId={PROJECT_ID} assetId={ASSET_ID}>
          {(src) => (
            <AnnotatorCanvas
              store={store}
              imageSrc={src}
              activeClass={null}
              onActivateClass={() => {}}
              onImageReady={(source) => {
                const visible = window.document.querySelector('[data-testid="annotator-image"]');
                setSameImage(source.image === visible ? "true" : "false");
                setRgb(Array.from(source.readRgb(WIDTH, HEIGHT).rgb).join(","));
              }}
            />
          )}
        </AssetImage>
      </div>
      <span data-testid="pixel-source-same-image">{sameImage}</span>
      <span data-testid="pixel-rgb">{rgb}</span>
    </VisionSetDataProvider>
  );
}
