"""Raw media to an approved, partitioned batch — M2's exit criterion in one pass.

A ten-second clip and a small folder of stills go in; fifty hash-deduplicated
assets in an approved batch of two jobs come out, with a pollable progress row
and a per-file report of what could not be read. Nothing here is annotated and
nothing is released — [`sdk_end_to_end.py`](sdk_end_to_end.py) covers that half
of the cycle. This one is about where assets *come from*.

Run it::

    uv run python examples/ingest_end_to_end.py [DESTINATION]

**This example needs ffmpeg.** Its sibling boasts of needing nothing: it builds
its PNGs out of ``zlib`` and ``struct`` and hands them to the SDK. A video
cannot be made that way — a clip is a container wrapped around a codec, and the
only honest way to write one is the tool that reads it. So the clip below is
generated by the same pinned ffmpeg command ``tests/fixtures/media.py`` uses,
duplicated rather than imported: that module is a *test* fixture, it imports
pytest, and its missing-binary answer is ``pytest.skip``, which means nothing in
a script.

The stills are Pillow's work rather than a second copy of the sibling's PNG
encoder. That encoder exists because M1 predates any image library; Pillow has
been a dependency since #16, and re-deriving a PNG by hand next to it would be
archaeology.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from uuid import UUID

from PIL import Image

from visionset.kernel.domain import (
    Asset,
    AssetProgress,
    BySize,
    DomainEvent,
    GeometryType,
    IngestJob,
    IngestResult,
    LabelClass,
)
from visionset.kernel.services import (
    BatchService,
    IngestService,
    JobService,
    ProjectService,
    SchemaService,
    SourceService,
    WorkspaceService,
)

#: Where the example puts its workspace unless told otherwise. Under
#: ``workspace-data/``, which the repository ignores by design.
DEFAULT_DEST = Path(__file__).resolve().parent / "workspace-data" / "ingest-e2e"

#: Bigger than the 64x48 the test fixtures use, and deliberately so. ``testsrc``
#: draws a pattern that moves a little between frames; below roughly 96x72 that
#: movement falls under what the scaler and the encoder can still resolve, and
#: consecutive frames come out **byte-identical**. Content addressing then does
#: exactly what it promises and collapses them, so a ten-second clip at five
#: frames a second yields forty assets rather than fifty — the feature working,
#: reported as a shortfall. 160x120 leaves a wide margin.
CLIP_SIZE = (160, 120)
CLIP_FPS = 10
CLIP_SECONDS = 10.0

#: Ten seconds at five frames a second is fifty assets — the number M2's exit
#: criterion names, and the reason the clip above is exactly ten seconds long.
EXTRACTION_FPS = 5.0

#: The same clip, decomposed coarsely. Ten frames, none of them new.
COARSE_FPS = 1.0

#: Fifty assets cut into two jobs. The partition is exact — disjoint, and their
#: union is the batch — which ``partition_assets`` guarantees rather than hopes.
JOB_SIZE = 25

STILL_COUNT = 3
STILL_SIZE = (48, 32)

#: What a folder of photographs really looks like: some of it is not a
#: photograph. This file is reported, not skipped — see stage (7).
STRAY_FILE = "notes.txt"

FFMPEG_MISSING = (
    "ffmpeg is not on PATH, and this example decomposes a video.\n"
    "Install it with `brew install ffmpeg` (macOS) or "
    "`sudo apt-get install ffmpeg` (Debian/Ubuntu), then run this again."
)

#: One class is enough. A batch cannot be approved by a project with no schema —
#: approval pins the active version forever — but this example writes no labels,
#: so the contract only has to exist.
CLASSES: tuple[LabelClass, ...] = (
    LabelClass(name="vehicle", geometry=GeometryType.BBOX, color="#2a9d8f"),
)


@dataclass(frozen=True)
class Summary:
    """What the run produced, for a reader and for the smoke test alike."""

    project_id: UUID
    schema_version: int
    clip_source_id: UUID
    clip_batch_id: UUID
    asset_ids: tuple[UUID, ...]
    clip_progress: IngestJob
    job_sizes: tuple[int, ...]
    rerun: IngestResult
    coarse_source_id: UUID
    coarse: IngestResult
    images: IngestResult
    image_progress: IngestJob
    asset_count: int
    thumbnailed: int
    events: tuple[str, ...]


# --- synthetic media ------------------------------------------------------


def write_clip(path: Path) -> Path:
    """A ``testsrc`` clip, byte-identical on every run of one ffmpeg build.

    The flags are ``tests/fixtures/media.write_video``'s, and each earns its
    place: ``+bitexact`` on both the container and the video stream strips the
    encoder version and the creation time that would otherwise make two runs of
    this command differ, and ``-g`` pins the keyframe interval so the decode is
    not at the mercy of a rate-control decision.

    Determinism holds *within* one ffmpeg build and not across versions. That is
    why nothing here — and nothing in the smoke test — asserts a hardcoded hash.
    """
    width, height = CLIP_SIZE
    path.parent.mkdir(parents=True, exist_ok=True)
    command = [
        "ffmpeg",
        "-nostdin",
        "-loglevel", "error",
        "-f", "lavfi",
        "-i", f"testsrc=size={width}x{height}:rate={CLIP_FPS}:duration={CLIP_SECONDS}",
        "-pix_fmt", "yuv420p",
        "-c:v", "libx264",
        "-preset", "ultrafast",
        "-g", str(CLIP_FPS),
        "-movflags", "+faststart",
        "-fflags", "+bitexact",
        "-flags:v", "+bitexact",
        "-y", str(path),
    ]  # fmt: skip
    result = subprocess.run(command, capture_output=True, text=True)
    if result.returncode != 0:
        raise SystemExit(f"ffmpeg could not generate {path.name}:\n{result.stderr}")
    return path


def write_stills(directory: Path) -> Path:
    """A few photographs and one thing that is not one.

    Each image gets its own pixels, so no pair deduplicates by accident and the
    three assets the ingest reports created are genuinely three.
    """
    directory.mkdir(parents=True, exist_ok=True)
    width, height = STILL_SIZE
    for index in range(STILL_COUNT):
        pixels = bytes(
            channel
            for y in range(height)
            for x in range(width)
            for channel in ((x * 5 + index * 61) % 256, (y * 7) % 256, (x + y + index * 23) % 256)
        )
        Image.frombytes("RGB", STILL_SIZE, pixels).save(
            directory / f"still-{index:03d}.png", format="PNG"
        )
    (directory / STRAY_FILE).write_text("shot on the coast road, tuesday\n")
    return directory


# --- the cycle ------------------------------------------------------------


def main(dest: Path) -> Summary:
    """Drive an empty directory to an approved batch, and report what happened.

    ``dest`` must not already be a workspace: this creates one. Everything the
    run produces lives under it.
    """
    if shutil.which("ffmpeg") is None:
        # Checked before anything is written, so a machine without the binary
        # leaves no half-made workspace behind. The kernel raises
        # MediaToolUnavailable for the same reason, with the same hint.
        raise SystemExit(FFMPEG_MISSING)

    seen: list[DomainEvent] = []

    with WorkspaceService.init(dest, name="ingest-end-to-end") as workspace:
        workspace.event_bus.subscribe(DomainEvent, seen.append)

        projects = ProjectService(workspace)
        schemas = SchemaService(workspace)
        sources = SourceService(workspace)
        ingest = IngestService(workspace)
        batches = BatchService(workspace)
        jobs = JobService(workspace)

        # (1) A project, its 1:1 dataset, and a labeling contract. Nothing here
        # writes a label, but a batch cannot be approved without a schema to pin.
        project = projects.create("dashcam", description="Ingest end-to-end demo")
        schema = schemas.create_version(project.id, CLASSES)
        _say(f"project {project.name!r} ({project.id}) with schema v{schema.version}")

        # (2) Ten seconds of video, registered as an origin. The extraction rate
        # is part of *what the source is*, not a per-run flag — "the same source
        # yields the same assets" only means something if the parameters that
        # decide those assets are recorded with it.
        clip = write_clip(dest / "clips" / "road.mp4")
        clip_source = sources.register_video(project.id, clip, extraction_fps=EXTRACTION_FPS)
        probed = clip_source.require_video().metadata
        _say(
            f"source registered: {probed.width}x{probed.height} {probed.codec} at "
            f"{probed.fps} fps for {probed.duration_seconds}s, "
            f"to be decomposed at {EXTRACTION_FPS} fps"
        )

        # (3) Decode, hash, store once, and materialize into a draft batch. The
        # decode happens outside every transaction: an out-of-process decoder
        # held inside a write transaction is how a single-writer SQLite store
        # starts reporting "database is locked".
        ingested = ingest.ingest(clip_source.id, batch_name="road-5fps")
        batch = batches.get(ingested.batch_id)
        first = ingested.assets[0]
        _say(
            f"{ingested.created} assets in batch {batch.name!r} ({batch.state.value}); "
            f"first is {first.uri.rsplit('/', 1)[-1]} at t={first.frame_timestamp}s"
        )

        # (4) Progress is a row, not a return value. It was written once per
        # item while the run was in flight, which is what makes it pollable from
        # another process — the contract the HTTP API and the UI will reuse.
        # 'total' is NULL for a clip: VideoMetadata carries no frame count by
        # design, and the number an ingest wants is what extraction produced.
        clip_progress = ingest.get(ingested.job_id)
        _say(
            f"job {clip_progress.state.value}: processed {clip_progress.processed}, "
            f"total {clip_progress.total if clip_progress.total is not None else 'unknown'}"
        )

        # (5) Approval freezes membership, pins the schema version forever, and
        # cuts the batch into jobs. The partition is exact — disjoint, union is
        # the batch — which is a domain guarantee, not a service's arithmetic.
        batch = batches.approve(batch.id, BySize(size=JOB_SIZE))
        batch_jobs = batches.jobs(batch.id)
        outstanding = jobs.batch_progress(batch.id)[AssetProgress.UNANNOTATED]
        _say(
            f"approved against schema v{batch.schema_version} into {len(batch_jobs)} jobs "
            f"of {'/'.join(str(len(job.progress)) for job in batch_jobs)}; "
            f"{outstanding} assets awaiting an annotator"
        )

        # (6) The idempotency property, demonstrated rather than asserted: the
        # same source ingested again creates nothing at all. It lands in a new
        # batch because the first one froze at approval — a batch is an
        # ephemeral unit of work and two may name the same assets.
        rerun = ingest.ingest(clip_source.id, batch_name="road-5fps-again")
        _say(
            f"re-ingested: {rerun.created} created, {rerun.deduplicated} already known "
            f"(same assets: {set(rerun.asset_ids) == set(ingested.asset_ids)})"
        )

        # (7) The same clip at another rate is a *different source* — the
        # parameters live on the source, so one file registered twice at two
        # rates is two origins. Its ten frames are nonetheless already in the
        # project: identity is content, and content does not care which source
        # produced it. Their recorded origin stays the first sighting's.
        coarse_source = sources.register_video(project.id, clip, extraction_fps=COARSE_FPS)
        coarse = ingest.ingest(coarse_source.id, batch_name="road-1fps")
        _say(
            f"same clip at {COARSE_FPS} fps is source {coarse_source.id} "
            f"(≠ {clip_source.id}): {len(coarse.assets)} frames, {coarse.created} new"
        )

        # (8) The other path. A directory can be listed, so the job states its
        # total before the first file — and the file that is not an image is
        # reported rather than skipped, because guessing which files an operator
        # meant to offer is a policy the kernel would be inventing.
        stills = write_stills(dest / "incoming")
        image_source = sources.register_images(project.id, stills)
        images = ingest.ingest(image_source.id, batch_name="stills")
        image_progress = ingest.get(images.job_id)
        # The report names each item and says what is wrong with it separately,
        # which is what lets a surface group by kind instead of reading prose.
        reported = ", ".join(
            f"{Path(failure.name).name} ({failure.kind.value}: {failure.reason})"
            for failure in images.failures
        )
        _say(
            f"directory: {image_progress.processed} of {image_progress.total} read, "
            f"{images.created} created, {images.failed} reported — {reported}"
        )
        _say(f"the run still {image_progress.state.value}: an unreadable file is not a failed run")

        # (9) Every asset got a preview at ingest, cached in the same blob store
        # as its content. A thumbnail hash is a cache key and not an identity:
        # it is in no release manifest, and nothing recomputes it to verify one.
        everything = _all_assets(ingested, rerun, coarse, images)
        thumbnailed = sum(1 for asset in everything.values() if asset.thumbnail_hash is not None)
        _say(f"{thumbnailed} of {len(everything)} assets carry a cached preview")

        _say(f"events seen, in order: {', '.join(event.name for event in seen)}")

        return Summary(
            project_id=project.id,
            schema_version=schema.version,
            clip_source_id=clip_source.id,
            clip_batch_id=batch.id,
            asset_ids=ingested.asset_ids,
            clip_progress=clip_progress,
            job_sizes=tuple(len(job.progress) for job in batch_jobs),
            rerun=rerun,
            coarse_source_id=coarse_source.id,
            coarse=coarse,
            images=images,
            image_progress=image_progress,
            asset_count=len(everything),
            thumbnailed=thumbnailed,
            events=tuple(event.name for event in seen),
        )


def _all_assets(*results: IngestResult) -> dict[UUID, Asset]:
    """Every distinct asset the run produced, keyed by id.

    Four ingests over three sources, and only fifty-three assets between them —
    which is the point. A dict rather than a list because the runs overlap by
    design, and counting the overlap twice would describe a project that does
    not exist.
    """
    return {asset.id: asset for result in results for asset in result.assets}


def _say(message: str) -> None:
    print(f"  · {message}")


# --- running it -----------------------------------------------------------


def _clear_previous_run(dest: Path) -> None:
    """Remove a previous run of this example, and refuse to remove anything else.

    Only ever called for :data:`DEFAULT_DEST`. A directory that holds anything
    other than what this example writes is not ours to delete, so it stops
    instead of guessing.
    """
    if not dest.exists():
        return
    if not dest.is_dir():
        raise SystemExit(f"refusing to run: {dest} exists and is not a directory")
    ours = {"visionset.db", "blobs", "clips", "incoming"}
    stray = {entry.name for entry in dest.iterdir()} - ours
    if stray:
        raise SystemExit(
            f"refusing to remove {dest}: it holds {', '.join(sorted(stray))}, "
            f"which this example did not write"
        )
    shutil.rmtree(dest)


def _run() -> None:
    if len(sys.argv) > 2:
        raise SystemExit(f"usage: {Path(sys.argv[0]).name} [DESTINATION]")
    if len(sys.argv) == 2:
        # A destination someone named is never removed automatically; if it is
        # already a workspace, WorkspaceService says so and stops.
        dest = Path(sys.argv[1]).resolve()
    else:
        dest = DEFAULT_DEST
        _clear_previous_run(dest)

    print(f"VisionSet ingest end-to-end · {dest}")
    summary = main(dest)
    print(
        f"\nDone. {len(summary.asset_ids)} assets from a "
        f"{CLIP_SECONDS:.0f}s clip in {len(summary.job_sizes)} jobs, "
        f"{summary.asset_count} in the project altogether.\n"
        f"Workspace left at {dest} — open it again with WorkspaceService.open()."
    )


if __name__ == "__main__":
    _run()
