"""Write `docs/content/mcp-tools.md` from the tool listing the server actually advertises.

**Generated rather than curated**, and the difference matters here more than it
does for most documentation. A tool description in this surface is not prose
about the code — it *is* the interface: it is the only thing a model reads before
choosing, and MCPServer ships it verbatim to every client. A hand-written reference
would be a second copy of a contract, free to drift from the one being served, and
the drift would be invisible until an agent behaved on the wrong information.

`docs/content/mcp.md` stays hand-written and stays the place to read *why* a tool exists,
what the coordinate frame rule is, and which gate guards what. This file is the
complete listing, exactly as served.

The destructive tools are included and marked, because a reference that omitted
them would be a reference to something nobody runs — but the default posture is
stated on every one of them.

Usage:

    uv run python scripts/export_mcp_tools.py            # write it
    uv run python scripts/export_mcp_tools.py --check     # fail if stale
"""

from __future__ import annotations

import inspect
import sys
from collections.abc import Callable
from pathlib import Path
from typing import Any

from visionset.mcp.main import DESTRUCTIVE_TOOLS, TOOLS

REPO_ROOT = Path(__file__).resolve().parent.parent

OUTPUT_PATH = REPO_ROOT / "docs" / "content" / "mcp-tools.md"

BANNER = """<!-- Generated by scripts/export_mcp_tools.py. Do not edit by hand. -->
# MCP tool reference

Every tool `visionset mcp` advertises, with the description it serves. Generated from the
server's own listing, so this cannot drift from what an agent is actually told.

Read [mcp.md](mcp.md) first for the parts that are decisions rather than listings — how a client
is configured, the coordinate-frame rule that makes `get_asset_image` safe to annotate from, the
error envelope, and the three gate words.
"""

#: No version and no timestamp anywhere in the output.
#:
#: The `scripts/generate_client.mjs` rule, for its reason: anything that varies
#: between two runs of an unchanged input fails the drift gate for a reason
#: nobody chose.


def _takes(tool: Callable[..., Any]) -> str:
    """What a tool takes, with a `?` on anything that has a default.

    Read off the real signature rather than off the JSON schema: MCPServer builds
    the schema from exactly this, and going through the server would mean
    starting one to document it.
    """
    parameters = inspect.signature(tool).parameters
    if not parameters:
        return "—"
    return ", ".join(
        f"`{name}`" if parameter.default is inspect.Parameter.empty else f"`{name}`?"
        for name, parameter in parameters.items()
    )


def render() -> str:
    """The whole document.

    Descriptions are quoted **first line only**. The full text is what the server
    serves and is frequently a page long — a reference that reprinted all of it
    would be unreadable, and the place to read the whole thing is the listing
    itself, which is what a client shows.
    """
    lines = [BANNER]
    for heading, table, note in (
        (
            "Always offered",
            TOOLS,
            # Counted from the table rather than written out. This sentence was
            # the last hand-maintained tool count in a generated document, and
            # it went stale twice in one run.
            f"{len(TOOLS)} tools, in the order an agent meets them: make a project, give it a "
            "schema, put images in it, work through them, promote, publish, export.",
        ),
        (
            "Offered only with `--allow-destructive`",
            DESTRUCTIVE_TOOLS,
            "Absent from the listing unless the server was started for them (#108). A `confirm` "
            "parameter is documented in the same listing an agent reads before choosing, so it "
            "is an instruction rather than a gate; a tool that is not advertised cannot be "
            "called with a flag.",
        ),
    ):
        lines.append(f"\n## {heading}\n")
        lines.append(f"{note}\n")
        lines.append("| Tool | Takes | What it does |")
        lines.append("| --- | --- | --- |")
        for tool, _hints in table:
            summary = (tool.__doc__ or "").strip().split("\n")[0]
            lines.append(f"| `{tool.__name__}` | {_takes(tool)} | {summary} |")
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    rendered = render()
    if "--check" in argv:
        current = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else ""
        if current != rendered:
            print(
                f"{OUTPUT_PATH.relative_to(REPO_ROOT)} is stale — run "
                f"`uv run python scripts/export_mcp_tools.py` and commit the result.",
                file=sys.stderr,
            )
            return 1
        print(f"{OUTPUT_PATH.relative_to(REPO_ROOT)} matches the served tool listing.")
        return 0
    OUTPUT_PATH.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
