"""Write the export-target table in `docs/content/releases.md` from the installed catalog.

**Generated rather than curated**, for the reason `export_mcp_tools.py` gives:
the catalog is derived from what the installed formats declare, every surface
renders that derivation, and a hand-written table would be a second copy free
to drift from the one `GET /export-targets` serves. The table lives inside a
hand-written document, so only the region between the two markers is owned
here; the prose around it stays the author's.

Usage:

    uv run python scripts/export_target_catalog.py            # rewrite the region
    uv run python scripts/export_target_catalog.py --check     # fail if stale
"""

from __future__ import annotations

import sys
from pathlib import Path

from visionset import wire
from visionset.formats.registry import exporters

REPO_ROOT = Path(__file__).resolve().parent.parent

DOCUMENT_PATH = REPO_ROOT / "docs" / "content" / "releases.md"

BEGIN = "<!-- export-targets:begin — generated by scripts/export_target_catalog.py; do not edit -->"
END = "<!-- export-targets:end -->"

COLUMNS = (
    "Target",
    "Label",
    "Family",
    "Format",
    "Tasks",
    "Geometries",
    "Recommended size",
    "Strategy",
)


def render() -> str:
    """The region between the markers, markers included."""
    lines = [
        BEGIN,
        "| " + " | ".join(COLUMNS) + " |",
        "| " + " | ".join("---" for _ in COLUMNS) + " |",
    ]
    for row in wire.export_targets(exporters()):
        hints = row["hints"]
        size = hints["recommended_size"]
        lines.append(
            "| "
            + " | ".join(
                (
                    f"`{row['name']}`",
                    str(row["label"]),
                    f"`{row['family']}`",
                    f"`{row['format']}`",
                    ", ".join(row["tasks"]) or "—",
                    ", ".join(row["geometries"]),
                    "—" if size is None else f"{size[0]}×{size[1]}",
                    "—"
                    if hints["recommended_strategy"] is None
                    else str(hints["recommended_strategy"]),
                )
            )
            + " |"
        )
    lines.append(END)
    return "\n".join(lines)


def _split(document: str) -> tuple[str, str, str]:
    """The text before the region, the region, and the text after it."""
    start = document.index(BEGIN)
    stop = document.index(END, start) + len(END)
    return document[:start], document[start:stop], document[stop:]


def main(argv: list[str]) -> int:
    document = DOCUMENT_PATH.read_text(encoding="utf-8")
    before, current, after = _split(document)
    rendered = render()
    relative = DOCUMENT_PATH.relative_to(REPO_ROOT)
    if "--check" in argv:
        if current != rendered:
            print(
                f"the export-target table in {relative} is stale — run "
                f"`uv run python scripts/export_target_catalog.py` and commit the result.",
                file=sys.stderr,
            )
            return 1
        print(f"the export-target table in {relative} matches the installed catalog.")
        return 0
    DOCUMENT_PATH.write_text(before + rendered + after, encoding="utf-8")
    print(f"wrote the export-target table in {DOCUMENT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
