/**
 * Every document in `docs/` appears in the documentation site's sidebar, exactly
 * once.
 *
 * `docs-site/src/sidebar.mjs` is written out by hand rather than autogenerated,
 * because autogeneration orders pages alphabetically and alphabetical is the wrong
 * order for documentation that has a reading order — `annotations` before `batches`
 * before `install` puts the last chapter first. The cost of writing it out is that a
 * document added to `docs/` and forgotten there is a page nothing navigates to, and
 * **nothing else would notice**: the projection builds it, Starlight serves it, the
 * link checker finds it linked from wherever it was cited, and the build is green.
 * This is what collects that cost.
 *
 * It reads `git ls-files`, i.e. the **index** rather than the working tree, on the
 * bargain the other scanners here run on: a merely *staged* document is checked
 * before any commit lands.
 *
 * `sidebar.mjs` has **no imports** so that this file can read it from the repository
 * root, where `docs-site/node_modules` need not exist. `pnpm test:scripts` runs
 * without installing the documentation site, and it has to stay that way — a gate
 * that needs a second install is one that gets skipped.
 */

import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { test } from "node:test";

import { sidebar, slugsIn } from "../../docs-site/src/sidebar.mjs";

const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");

/** Tracked documentation, from the index. */
function documents() {
  const listed = spawnSync("git", ["-C", REPO, "ls-files", "docs/*.md", "docs/**/*.md"], {
    encoding: "utf8",
  });
  assert.equal(listed.status, 0, "git ls-files must succeed");
  return [...new Set(listed.stdout.split("\n").filter(Boolean))];
}

/**
 * The slug Starlight serves a document at, mirroring `sync-docs.mjs`.
 *
 * `docs/README.md` is the site root and its slug is the empty string; a `README.md`
 * in any other directory is that directory's index.
 */
function slugOf(file) {
  const parts = file.replace(/^docs\//, "").replace(/\.md$/, "").split("/");
  if (parts[parts.length - 1] === "README") parts.pop();
  return parts.join("/");
}

test("every document in docs/ is somewhere in the sidebar", () => {
  const listed = new Set(slugsIn());
  const missing = documents()
    .filter((file) => !listed.has(slugOf(file)))
    .map((file) => `${file}  (would be slug "${slugOf(file)}")`);

  assert.deepEqual(
    missing,
    [],
    `documents nothing navigates to — add them to docs-site/src/sidebar.mjs:\n  ${missing.join("\n  ")}`,
  );
});

test("the sidebar names no page that does not exist", () => {
  const real = new Set(documents().map(slugOf));
  const phantom = slugsIn().filter((slug) => !real.has(slug));

  assert.deepEqual(
    phantom,
    [],
    `sidebar entries with no document behind them:\n  ${phantom.join("\n  ")}`,
  );
});

test("no document is listed twice", () => {
  // Starlight would render both, and the second is invisible to a reader who found
  // the first — so this is not tidiness, it is two navigation paths to one page.
  const seen = new Map();
  for (const slug of slugsIn()) seen.set(slug, (seen.get(slug) ?? 0) + 1);
  const repeated = [...seen].filter(([, count]) => count > 1).map(([slug]) => slug);

  assert.deepEqual(repeated, [], `listed more than once: ${repeated.join(", ")}`);
});

test("the scan reads the sidebar rather than agreeing with an empty one", () => {
  // Every assertion above is satisfied by a sidebar this file failed to parse: an
  // empty roster makes "names no page that does not exist" and "no document is
  // listed twice" both vacuously true. The repository has forty-odd documents.
  assert.ok(sidebar.length > 0, "the sidebar has no groups — the import is not resolving");
  assert.ok(slugsIn().length > 30, `only ${slugsIn().length} entries found — the walk is not descending`);
});
